name: PHPStan
on: [workflow_dispatch, pull_request]

env:
  PLUGIN_CODE: StripeWebhook
  PLUGIN_PACKAGE_NAME: 'ec-cube/stripewebhook'

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        eccube-versions: ['4.3']
        php-versions: [ '8.2' ]
        database: [ 'mysql' ]
        include:
          - database: mysql
            database_url: mysql://root:password@127.0.0.1:3306/eccube_db
            database_server_version: 5.7
            database_charset: utf8mb4
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: kurozumi/eccube-plugin-phpstan@v1.0.5
        with:
          plugin-code: ${{ env.PLUGIN_CODE }}
          plugin-package-name: ${{ env.PLUGIN_PACKAGE_NAME }}
          eccube-versions: ${{ matrix.eccube-versions }}
          php-versions: ${{ matrix.php-versions }}
          database-url: ${{ matrix.database_url }}
          database-server-version: ${{ matrix.database_server_version }}
          database-charset: ${{ matrix.database_charset }}
